### ISSUE TITLE
黒メニューだとアイコンきえる

### ISSUE THREAD

**Issue by typester** [soh335/ScreenCaptureBox#2]
![](https://dl.dropbox.com/s/dcqnosei9qqo1vf/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%202015-12-11%2016.59.34.png?dl=0)

このなぞの空白部分です

**Comment by soh335** [comment]
![](https://dl.dropbox.com/s/gjwub59ebe1mkjp/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%202015-12-15%2011.55.38.png?dl=0)

fixed
